[package]
name = "payment_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.4.0"
tracing = "0.1.41"
thiserror = "2.0.17"
rust_decimal = "1.39"
tracing-subscriber = "0.3.20"
tokio = { version = "1.48.0", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
